//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEgitim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KursLink
    {
        public int kurskayıtid { get; set; }
        public string kursLinks { get; set; }
        public Nullable<int> kursid { get; set; }
        public string videoad { get; set; }
        public string icerikbaslik { get; set; }
    
        public virtual Kurs Kurs { get; set; }
    }
}
