//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEgitim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurs
    {
        public int KursId { get; set; }
        public string kursbaslik { get; set; }
        public string aciklama { get; set; }
        public string Dil { get; set; }
        public string Düzey { get; set; }
        public Nullable<int> kategoriid { get; set; }
        public string kursgoruntu { get; set; }
        public Nullable<int> kullaniciid { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Kategori Kategori { get; set; }
    }
}
