//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEgitim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public int Yorumid { get; set; }
        public string Yorum1 { get; set; }
        public Nullable<int> kullaniciid { get; set; }
        public Nullable<int> kursid { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Kurs Kurs { get; set; }
    }
}
